import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { TabContents } from './Components/TabContents'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nischal Basyal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TabContents />
    

      <footer className={styles.footer}>
          <span>
          </span>
          Copyright &copy; 2022 Nischal Basyal
      </footer>
    </div>
  )
}
