import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar } from './Components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nischal Basyal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <footer className={styles.footer}>
          <span className={styles.logo}>
          </span>
          Contact Nischal Basyal here:<a href="https://chat.test.nischalbasyal.com">Trench Chat</a>
      </footer>
    </div>
  )
}
